[workspace]
authors = ["nmarticorena <nicolas.marticorena.vidal@gmail.com>"]
channels = ["conda-forge"]
name = "rmmi.github.io"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]
test = "python3 -m http.server -b 0.0.0.0"

[dependencies]
python = ">=3.13.5,<3.14"
